### ISSUE TITLE
Does this project contain someip

### ISSUE THREAD

**Issue by jacklorlf** [openAUTOSAR/classic-platform#1]
Hi
Does this project contain someip, please point it out if so, I didn’t find it, The SD is someip sd?

**Comment by openAUTOSAR** [comment]
Hi and sorry for the late response.

Currently there is no module for SOME/IP included in the takeover of the Arctic Core Autosar implementation, which is more or less based on AUTOSAR v4.2.2. The SD implementation is a generic AUTOSAR Service Discovery, which uses SOME/IP-SD messages too:

> The AUTOSAR Service Discovery module offers functionality to detect and offer available services – i.e. functional entities – within the vehicle network. To do so, it makes use of the IP Multicast and so called SOME/IP-SD messages.

If you're looking for a full implementation of SOME/IP then I suggest to use [vsomeip](https://github.com/GENIVI/vsomeip) from the GENIVI alliance / BMW.
